const apiRouter = require("express").Router();
const { topicsRouter } = require("../routers/topicsRouter");
const { usersRouter } = require("../routers/usersRouters");
const { articlesRouter } = require("../routers/articlesRouters");
const { commentsRouter } = require("../routers/commentsRouters");
apiRouter.use("/topics", topicsRouter);
apiRouter.use("/users", usersRouter);
apiRouter.use("/articles", articlesRouter);
apiRouter.use("/comments", commentsRouter);
module.exports = { apiRouter };
